export const hexagons = [
  {
    place: 'Стадион',
    time: '18 Июня',
    hour: '20:00',
    link: 'https:google.com',
    opponent_1: 'Павлович',
    opponent_2: 'Волоков',
    id: 1,
  },
  {
    place: 'Моки',
    time: '19 Июня',
    link: 'https:google.com',
    hour: '21:00',
    opponent_1: 'Махачев',
    opponent_2: 'Гейджи',
    id: 2,
  },
  {
    place: 'Баскет-Холл',
    time: '22 Июня',
    link: 'https:google.com',
    hour: '19:00',
    opponent_1: 'Джонс',
    opponent_2: 'Миочич',
    id: 3,
  },
  {
    place: 'Мэдисон-сквер',
    time: '17 Июля',
    link: 'https:google.com',
    hour: '17:00',
    opponent_1: 'Холлоуэй',
    opponent_2: 'Волконовский',
    id: 4,
  },
  {
    place: 'Лужники',
    time: '1 Августа',
    link: 'https:google.com',
    hour: '13:00',
    opponent_1: 'Спартак',
    opponent_2: 'ЦСКА',
    id: 5,
  },
]
